# Generated by Django 4.1.1 on 2022-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetect', '0002_remove_userprofile_bio_alter_userprofile_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
