# Generated by Django 4.1.1 on 2022-10-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetect', '0003_alter_userprofile_face_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
