# Generated by Django 4.1.2 on 2022-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('productNo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=20)),
                ('mimg_path', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('explain', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
