# Generated by Django 4.1.2 on 2022-10-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "productNo",
                    models.IntegerField(
                        default=0, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.category"
            ),
        ),
    ]
